---
  - name: "udpate apt repo"
    action: apt update-cache=yes

  - name: install python-software-properties
    action: apt name='python-software-properties' state=installed

  - name: add nginx ppa
    action: apt_repository repo=ppa:nginx/stable state=present

  - name: install system packages required by the Sync Server
    action: apt pkg=$item state=installed
    with_items:
      - python-dev
      - python-setuptools
      - git-core
      - postgresql
      - libpq-dev
      - nginx
      - make

  - name: ensure ssl directory
    action: file dest=/etc/nginx/ssl state=directory

  - name: create self-signed SSL cert
    command: openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN=${app_name}" -days 3650 -keyout /etc/nginx/ssl/server.key -out /etc/nginx/ssl/server.crt -extensions v3_ca creates=/etc/nginx/ssl/server.crt
    notify: restart nginx

  - name: install pip
    action: easy_install name=pip

  - name: install various libraries with pip
    action: pip name=$item state=present
    with_items:
      - virtualenv
      - mercurial
      - psycopg2
      - gunicorn
      - uwsgi

  - name: install supervisor with pip pre
    action: pip name=supervisor state=present extra_args='--pre'

  - name: remove default nginx site
    action: file path=/etc/nginx/sites-enabled/default state=absent

  - name: write nginx.conf
    action: template src=../templates/nginx.conf dest=/etc/nginx/nginx.conf

  - name: create supervisord config folder
    action: file dest=/etc/supervisor state=directory owner=root

  - name: create supervisord config
    action: template src=../templates/supervisord.conf dest=/etc/supervisord.conf

  - name: create supervisord init script
    action: template src=../templates/supervisord.sh dest=/etc/init.d/supervisord mode=0755

  - name: start supervisord service and have it run during system startup
    action: service name=supervisord state=started enabled=yes

  - name: create webapps directory
    action: file dest=/opt/webapps state=directory
